//
//  Bagels.swift
//  Applebaum_Ian_Lab1
//
//  Created by Ian Applebaum on 2/13/20.
//  Copyright © 2020 Ian Applebaum. All rights reserved.
//

import Foundation
class Bagels {
	/// `number` is our struct for comparison. `number` has a `first`, `second`, and `third` value to be compared.
	/**
	Player's guess:
	~~~
	var guess = number(first: 3, second: 2, Third: 1)
	~~~
	The computer could generate a number for comparison:
	~~~
	var randomNumber = number(first: 4, second: 5, Third: 6)
	~~~
	These can be compared simply by
	~~~
	if guess == randomNumber{
		print("numbers match")
	}
	~~~
	*/
	struct number: Equatable {
		var first:Int
		var second:Int
		var Third:Int
		static func == (lhs: number, rhs: number) -> Bool {
			return lhs.first == rhs.first && lhs.second == rhs.second && lhs.Third == rhs.Third
		}
		func printNumber() -> String {
			return "\(first)\(second)\(Third)"
		}
	}
	/// Checks for the users first guess Int<10
	/// - Parameters:
	///   - guess: the number the user guessed
	///   - randomNumber: number generated by the computer
	///   - result: Either FERMI when you guessed right! PICO if the number is right but hte wrong order. BAGELS you guessed wrong!
	fileprivate func checkFirstGuess(_ guess: Bagels.number, _ randomNumber: Bagels.number, _ result: inout String) -> hints {
		result.append("guess = \(guess.printNumber()), ")
		switch guess.first {
		case randomNumber.first:
//			result.append("FERMI")
			return .fermi
		case randomNumber.second:
//			result.append("PICO")
			return .pico
		case randomNumber.Third:
//			result.append("PICO")
			return .pico
		default:
			return .bagels
//			result.append("BAGELS")
		}
	}
	/// Checks for the users second guess Int<10
	/// - Parameters:
	///   - guess: the number the user guessed
	///   - randomNumber: number generated by the computer
	///   - result: Either FERMI when you guessed right! PICO if the number is right but hte wrong order. BAGELS you guessed wrong!
	fileprivate func checkSecondGuess(_ guess: Bagels.number, _ randomNumber: Bagels.number, _ result: inout String) -> hints{
		switch guess.second {
		case randomNumber.second:
//			result.append(" FERMI")
			return .fermi
		case randomNumber.first:
//			result.append(" PICO")
			return .pico
		case randomNumber.Third:
//			result.append(" PICO")
			return .pico
		default:
			return .bagels
//			result.append(" BAGELS")
		}
	}
	fileprivate func addFermi(_ result: inout String) {
		result.append(" FERMI")
	}
	
	fileprivate func addPICO(_ result: inout String) {
		result.append(" PICO")
	}
	
	/// Checks for the users third guess Int<10
	/// - Parameters:
	///   - guess: the number the user guessed
	///   - randomNumber: number generated by the computer
	///   - result: Either FERMI when you guessed right! PICO if the number is right but hte wrong order. BAGELS you guessed wrong!
	fileprivate func checkThirdGuess(_ guess: Bagels.number, _ randomNumber: Bagels.number, _ result: inout String) -> hints{
			switch guess.Third {
			case randomNumber.Third:
//				addFermi(&result)
				return .fermi
			case randomNumber.second:
//				addPICO(&result)
				return .pico
			case randomNumber.first:
//				result.append(" PICO")
				return .pico
			default:
				return .bagels
	//			result.append(" BAGELS")
			}
		}
	
	/// Get the users guess from the keyboard and convert it to `number` struct
	/// - Parameter guess: the `number` struct to hold the users guess.
	fileprivate func getUserGuess(_ guess: inout Bagels.number) {
		let keyboad = readLine(strippingNewline: true) ?? ""
		let first: Int = Int(keyboad[0]) ?? 0
		let second: Int = Int(keyboad[1]) ?? 0
		let third: Int = Int(keyboad[2]) ?? 0
		guess = number(first: first, second: second, Third: third)
		if guess == number(first: 0, second: 0, Third: 0){
			print("000 NOT VALID TRY AGAIN")
			getUserGuess(&guess)
		}
		else if first < 10 {
			if guess == number(first: first, second: 0, Third: 0){
				print("\(first)00 NOT VALID TRY AGAIN")
				getUserGuess(&guess)
			}
		}
		if first < 10 && second < 10 {
			if guess == number(first: first, second: second, Third: 0){
				print("\(first)\(second)0 NOT VALID TRY AGAIN")
				getUserGuess(&guess)
			}
		}
	}
	
	/// Asks the player if they would like to play again. 1 for yes. 0 for no.
	fileprivate func wouldYouliketoplayagain() {
		print("Would you like to play again?\nYes!(1)\nNo(0)")
		let keyboad = readLine(strippingNewline: true) ?? ""
		let response: responses = responses(rawValue: Int(keyboad) ?? 3) ?? .oops
		switch response {
		case .yes:
			playGame()
		case .no:
			print("Thanks for playing!")
			exit(1)
		default:
			print("Oops try again?")
			wouldYouliketoplayagain()
		}
	}
	
	/// Console gets sassy if you take too many tries to win
	/// - Parameter numberOfGuesses: number of times the player guessed a number
	fileprivate func snarkyGameWinText(_ numberOfGuesses: Int) {
		if numberOfGuesses > 3{
			print("Congratulations YOU WON! Only took you \(numberOfGuesses) tries! 😜")
		}
		else if numberOfGuesses < 3{
			print("WOW! YOU WON in just \(numberOfGuesses) guesses!")
		}
	}
	
	fileprivate func addBagels(_ result: inout String) {
		result.append("BAGELS")
	}
	
	fileprivate func checkForPICO(_ firstGuess: Bagels.hints, _ result: inout String, _ secondGuess: Bagels.hints, _ thirdGuess: Bagels.hints) {
		if firstGuess == .pico {
			addPICO(&result)
		}
		if secondGuess == .pico {
			addPICO(&result)
		}
		if thirdGuess == .pico {
			addPICO(&result)
		}
	}
	
	fileprivate func checkForFERMI(_ firstGuess: Bagels.hints, _ result: inout String, _ secondGuess: Bagels.hints, _ thirdGuess: Bagels.hints) {
		if firstGuess == .fermi {
			addFermi(&result)
		}
		if secondGuess == .fermi {
			addFermi(&result)
		}
		if thirdGuess == .fermi {
			addFermi(&result)
		}
	}
	
	fileprivate func checkForBAGELS(_ firstGuess: Bagels.hints, _ secondGuess: Bagels.hints, _ thirdGuess: Bagels.hints, _ result: inout String) {
		if firstGuess == .bagels && secondGuess == .bagels && thirdGuess == .bagels {
			addBagels(&result)
		}
	}
	
	fileprivate func printStars() {
		var stars = ""
		for _ in 0...100{
			stars.append("*")
		}
		print(stars)
	}
	
	fileprivate func welcome() {
		print("WELCOME enter a three digit number such as 123.\nDo not enter any 0s!\nIf you guess the same number as me you win!\nI'll give you hints along the way.\nIf you guess a number right I'll say FERMI!\nIf you get a number right but out of order I'll say PICO.\nIf you just don't get it I'll say BAGEL!")
		print("Lets begin!")
	}
	
	/**
	1. Generate the secret number
	2. Determine whether the current guess is a winner
	3. Evaluate the current guess and print hints
	*/
	public func playGame(){
		welcome()
		printStars()
		let randomNumber = generateRandomNumber()
		var guess = number(first: 0, second: 0, Third: 0)
		var result = ""
		var numberOfGuesses = 0
		print("Guess a number!")
		repeat{
			numberOfGuesses += 1
			result = ""
			getUserGuess(&guess)
			let firstGuess = checkFirstGuess(guess, randomNumber, &result)
			let secondGuess = checkSecondGuess(guess, randomNumber, &result)
			let thirdGuess = checkThirdGuess(guess, randomNumber, &result)
			checkForPICO(firstGuess, &result, secondGuess, thirdGuess)
			checkForFERMI(firstGuess, &result, secondGuess, thirdGuess)
			checkForBAGELS(firstGuess, secondGuess, thirdGuess, &result)
			print(result)
		}while (guess != randomNumber)
		snarkyGameWinText(numberOfGuesses)
		wouldYouliketoplayagain()
	}
	/// Simple Enum for yes or no responses
	enum responses:Int {
		case no
		case yes
		case oops
	}
	/// The hint to the user
	enum hints {
		case fermi
		case pico
		case bagels
	}
	/// generates the random `number` for the game. Returning struct `number`
	private func generateRandomNumber()->number{
		let first = Int.random(in: 1 ..< 10)
		let second = Int.random(in: 1 ..< 10)
		let third = Int.random(in: 1 ..< 10)
		return number(first: first, second: second, Third: third)
	}
}
